export const CHANGEINDEXDATA='changeindexdata'
export const CHANGECARTLIST='changeCartList'
export const CHANGECOUNTMUTAION = 'changeCountMutation'
export const CHANGESELECTEDMUTATION ='changeSelectedMutation'
export const CHANGEALLSELECTEDMUTATION='changeAllSelectedMutation'